name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: AKIAVRUVPYUPOZMQH6P7
      AWS_SECRET_ACCESS_KEY: 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

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        npm install -g @angular/cli

    - name: Build Angular project
      run: ng build --configuration=production

    - name: Check authentication status
      run: aws sts get-caller-identity
      if: always()  # Führe diesen Schritt immer aus, unabhängig vom vorherigen Schritt

    - name: Display authentication status
      run: echo "Authentication successful"
      if: success()  # Führe diesen Schritt nur aus, wenn der vorherige Schritt erfolgreich war
